=== akeneo/pim-community-dev/components/catalogs/back/src/Infrastructure/Symfony/Resources/meta-schemas/product-0.0.1.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://api.akeneo.com/mapping/product/0.0.1/schema",
  "type": "object",
  "properties": {
    "$id": { "$ref": "#/$defs/$id" },
    "$schema": { "$ref": "#/$defs/$schema" },
    "$comment": { "$ref": "#/$defs/$comment" },
    "$defs": { "$ref": "#/$defs/$defs" },
    "title": { "$ref": "#/$defs/title" },
    "description": { "$ref": "#/$defs/description" },
    "type": { "const": "object" },
    "properties": {
      "type": "object",
      "additionalProperties": { "$ref": "#/$defs/property" },
      "default": {}
    }
  },
  "$defs": {
    "$id": {
      "$comment": "Non-empty fragments not allowed.",
      "pattern": "^[^#]*#?$"
    },
    "$schema": { "$ref": "#/$defs/uriString" },
    "$comment": {
      "type": "string"
    },
    "$defs": {
      "type": "object",
      "additionalProperties": { "$ref": "#/$defs/property" }
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "propertyType": {
      "enum": [
        "string"
      ]
    },
    "property": {
      "type": "object",
      "properties": {
        "title": { "$ref": "#/$defs/title" },
        "description": { "$ref": "#/$defs/description" },
        "type": { "$ref": "#/$defs/propertyType" }
      },
      "additionalProperties": false,
      "required": ["type"]
    },
    "uriString": {
      "type": "string",
      "format": "uri"
    }
  },
  "additionalProperties": false
}

=== akeneo/pim-community-dev/components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/valid/0.0.1.json
{
  "$id": "https://example.com/product",
  "$schema": "https://api.akeneo.com/mapping/product/0.0.1/schema",
  "$comment": "My first schema !",
  "title": "Product Mapping",
  "description": "JSON Schema describing the structure of products expected by our application",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "body_html": {
      "title": "Description",
      "description": "Product description in raw HTML",
      "type": "string"
    }
  }
}
