=== akeneo/pim-community-dev/components/catalogs/back/src/Infrastructure/Symfony/Resources/meta-schemas/product-0.0.11.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://api.akeneo.com/mapping/product/0.0.11/schema",
  "type": "object",
  "properties": {
    "$id": { "$ref": "#/$defs/$id" },
    "$schema": { "$ref": "#/$defs/$schema" },
    "$comment": { "$ref": "#/$defs/$comment" },
    "$defs": { "$ref": "#/$defs/$defs" },
    "title": { "$ref": "#/$defs/title" },
    "description": { "$ref": "#/$defs/description" },
    "type": { "const": "object" },
    "properties": {
      "type": "object",
      "properties": {
        "uuid": { "$ref": "#/$defs/uuidProperty" }
      },
      "additionalProperties": { "$ref": "#/$defs/property" },
      "default": {},
      "required": ["uuid"]
    },
    "required": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "uniqueItems": true,
      "default": [],
      "minItems": 1
    }
  },
  "$defs": {
    "$id": {
      "$comment": "Non-empty fragments not allowed.",
      "pattern": "^[^#]*#?$"
    },
    "$schema": { "$ref": "#/$defs/uriString" },
    "$comment": {
      "type": "string"
    },
    "$defs": {
      "type": "object",
      "additionalProperties": { "$ref": "#/$defs/property" }
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "property": {
      "type": "object",
      "properties": {
        "title": { "$ref": "#/$defs/title" },
        "description": { "$ref": "#/$defs/description" },
        "type": {
          "enum": [
            "string",
            "number",
            "boolean",
            "array"
          ]
        },
        "format": {
          "enum": [
            "date-time",
            "uri"
          ]
        },
        "items": {
          "type": "object",
          "properties": {
            "type": {
              "enum": [
                "string"
              ]
            }
          },
          "additionalProperties": false,
          "required": ["type"]
        },
        "minLength": {
          "type": "integer",
          "minimum": 0
        },
        "maxLength": {
          "type": "integer",
          "minimum": 0
        },
        "pattern": {
          "type": "string",
          "format": "regex"
        },
        "minimum": {
          "type": "number"
        },
        "maximum": {
          "type": "number"
        },
        "enum": {
          "type": "array"
        }
      },
      "additionalProperties": false,
      "if": {
        "properties": {
          "type": {
            "const": "array"
          }
        }
      },
      "then": {
        "required": ["items"]
      },
      "required": ["type"],
      "dependentSchemas": {
        "format": {
          "properties": {
            "type": {
              "enum": [
                "string"
              ]
            }
          },
          "required": ["type"]
        },
        "items": {
          "properties": {
            "type": {
              "enum": [
                "array"
              ]
            }
          },
          "required": ["type"]
        },
        "minLength": {
          "properties": {
            "type": {
              "enum": [
                "string"
              ]
            }
          },
          "required": ["type"]
        },
        "maxLength": {
          "properties": {
            "type": {
              "enum": [
                "string"
              ]
            }
          },
          "required": ["type"]
        },
        "pattern": {
          "properties": {
            "type": {
              "enum": [
                "string"
              ]
            }
          },
          "required": ["type"]
        },
        "minimum": {
          "properties": {
            "type": {
              "enum": [
                "number"
              ]
            }
          },
          "required": ["type"]
        },
        "maximum": {
          "properties": {
            "type": {
              "enum": [
                "number"
              ]
            }
          },
          "required": ["type"]
        },
        "enum": {
          "if": {
            "properties": {
              "type": {
                "const": "string"
              }
            }
          },
          "then": {
            "properties": {
              "enum": {
                "items": {
                  "type": "string"
                }
              }
            }
          },
          "else": {
            "if": {
              "properties": {
                "type": {
                  "const": "number"
                }
              }
            },
            "then": {
              "properties": {
                "enum": {
                  "items": {
                    "type": "number"
                  }
                }
              }
            }
          },
          "required": ["type"]
        }
      }
    },
    "uriString": {
      "type": "string",
      "format": "uri"
    },
    "uuidProperty": {
      "type": "object",
      "properties": {
        "title": { "$ref": "#/$defs/title" },
        "description": { "$ref": "#/$defs/description" },
        "type": { "const": "string" }
      },
      "additionalProperties": false,
      "required": ["type"]
    }
  },
  "additionalProperties": false
}

=== akeneo/pim-community-dev/components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/valid/0.0.9.json
{
    "$id": "https://example.com/product",
    "$schema": "https://api.akeneo.com/mapping/product/0.0.8/schema",
    "$comment": "My first schema !",
    "title": "Product Mapping",
    "description": "JSON Schema describing the structure of products expected by our application",
    "type": "object",
    "properties": {
        "uuid": {
            "title": "Product uuid",
            "type": "string"
        },
        "name": {
            "type": "string",
            "pattern": ".*"
        },
        "body_html": {
            "title": "Description",
            "description": "Product description in raw HTML",
            "type": "string"
        },
        "is_published": {
            "type": "boolean"
        },
        "height": {
            "type": "number",
            "minimum": 0,
            "maximum": 100
        },
        "release_date": {
            "type": "string",
            "format": "date-time"
        },
        "thumbnail": {
            "type": "string",
            "format": "uri"
        }
    }
}
