=== akeneo/pim-community-dev/components/catalogs/back/src/Infrastructure/Symfony/Resources/meta-schemas/product-0.0.6.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://api.akeneo.com/mapping/product/0.0.6/schema",
  "type": "object",
  "properties": {
    "$id": { "$ref": "#/$defs/$id" },
    "$schema": { "$ref": "#/$defs/$schema" },
    "$comment": { "$ref": "#/$defs/$comment" },
    "$defs": { "$ref": "#/$defs/$defs" },
    "title": { "$ref": "#/$defs/title" },
    "description": { "$ref": "#/$defs/description" },
    "type": { "const": "object" },
    "properties": {
      "type": "object",
      "properties": {
        "uuid": { "$ref": "#/$defs/uuidProperty" }
      },
      "additionalProperties": { "$ref": "#/$defs/property" },
      "default": {},
      "required": ["uuid"]
    }
  },
  "$defs": {
    "$id": {
      "$comment": "Non-empty fragments not allowed.",
      "pattern": "^[^#]*#?$"
    },
    "$schema": { "$ref": "#/$defs/uriString" },
    "$comment": {
      "type": "string"
    },
    "$defs": {
      "type": "object",
      "additionalProperties": { "$ref": "#/$defs/property" }
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "property": {
      "type": "object",
      "properties": {
        "title": { "$ref": "#/$defs/title" },
        "description": { "$ref": "#/$defs/description" },
        "type": {
          "enum": [
            "string",
            "number",
            "boolean"
          ]
        },
        "format": {
          "enum": [
            "date-time",
            "uri"
          ]
        },
        "minLength": {
          "type": "integer",
          "minimum": 0
        },
        "maxLength": {
          "type": "integer",
          "minimum": 0
        }
      },
      "additionalProperties": false,
      "required": ["type"],
      "dependentSchemas": {
        "format": {
          "properties": {
            "type": {
              "enum": [
                "string"
              ]
            }
          },
          "required": ["type"]
        }
      }
    },
    "uriString": {
      "type": "string",
      "format": "uri"
    },
    "uuidProperty": {
      "type": "object",
      "properties": {
        "title": { "$ref": "#/$defs/title" },
        "description": { "$ref": "#/$defs/description" },
        "type": { "const": "string" }
      },
      "additionalProperties": false,
      "required": ["type"]
    }
  },
  "additionalProperties": false
}

=== akeneo/pim-community-dev/components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/valid/0.0.5.json
{
    "$id": "https://example.com/product",
    "$schema": "https://api.akeneo.com/mapping/product/0.0.5/schema",
    "$comment": "My first schema !",
    "title": "Product Mapping",
    "description": "JSON Schema describing the structure of products expected by our application",
    "type": "object",
    "properties": {
        "uuid": {
            "title": "Product uuid",
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "body_html": {
            "title": "Description",
            "description": "Product description in raw HTML",
            "type": "string"
        },
        "is_published": {
            "type": "boolean"
        },
        "height": {
            "type": "number"
        },
        "meta_description": {
            "type": "string",
            "minLength": 50,
            "maxLength": 160
        }
    }
}
